(function(){
  const STORAGE_KEY='truck-inspector-pro-static-v3';
  const form=document.getElementById('truckForm');
  const toastEl=document.getElementById('toast');
  const fieldIds=['driverName','date','route','vehicleLicense','odometer','driverSignature','reviewedBySupervisor','mechanicInitials','inspectedBySupervisor','inspectionDate'];
  const statusIds=['oilLevel','coolantLevel','batteryCorrosion','oilLeaks','brakeFluidLeaks','airFilter','windshield','wiperBlades','horn','mirrors','hazardLights','headlights','hiBeam','taillights','brakeLights','turnSignals','cleanClear','locksProperly','liftSupports','ladderRack','hose','electricHoseReel','hoseReelGrease','screenFilter','sprayGun','tightenHoseClamps','runPumpLeaks','bgsNoLeaks','hoseFilter','servicedRegularly','labeled','maintainedProperly','safetyGlasses','spareClothes','pesticideGloves','nonPesticideGloves','mixingApron','polyOvershoes','respiratorContainer','cellPhone','vehicleCameraSystem','printerCondition','camerasAdjusted','printerPaper','workingProperly','medicalPosting','labelSdsAccess','spillKit','eyeWash','fireExtinguisher','measuringDevice','serviceContainersLabeled','flashlight','properBelt','safetyCone','currentRegistration','currentInsurance','wheelsPacket','gasCard','importantPapersEnvelope'];
  const adIds=['bodyCondition','decalCondition','vehicleInteriorClean','paperworkOrganized','cleanOrganized','appearance','applicationEquipmentClean','bgsClean','bgsWorking','idBadge','blackPolishedShoes','cleanClarkHat'];
  const sectionStatus={vehicle:['oilLevel','coolantLevel','batteryCorrosion','oilLeaks','brakeFluidLeaks','airFilter','windshield','wiperBlades','horn','mirrors','hazardLights','headlights','hiBeam','taillights','brakeLights','turnSignals'],equipment:['cleanClear','locksProperly','liftSupports','ladderRack','hose','electricHoseReel','hoseReelGrease','screenFilter','sprayGun','tightenHoseClamps','runPumpLeaks','bgsNoLeaks','hoseFilter','servicedRegularly','labeled','maintainedProperly'],ppe:['safetyGlasses','spareClothes','pesticideGloves','nonPesticideGloves','mixingApron','polyOvershoes','respiratorContainer'],devices:['cellPhone','vehicleCameraSystem','printerCondition','camerasAdjusted','printerPaper','workingProperly'],documents:['medicalPosting','labelSdsAccess','spillKit','eyeWash','fireExtinguisher','measuringDevice','serviceContainersLabeled','flashlight','properBelt','safetyCone','currentRegistration','currentInsurance','wheelsPacket','gasCard','importantPapersEnvelope']};

  const PDF_MAP={
    text:{driverName:[{page:0,x:270,y:720},{page:1,x:112,y:697}],date:[{page:0,x:465,y:742},{page:1,x:75,y:675}],route:[{page:0,x:476,y:720},{page:1,x:238,y:675}],vehicleLicense:[{page:0,x:168,y:693},{page:1,x:390,y:697}],odometer:[{page:0,x:466,y:693},{page:1,x:445,y:675}],driverSignature:[{page:0,x:150,y:50},{page:1,x:150,y:52}],reviewedBySupervisor:[{page:0,x:545,y:50}],mechanicInitials:[{page:0,x:150,y:30}],inspectedBySupervisor:[{page:0,x:380,y:30}],inspectionDate:[{page:0,x:555,y:30}]},
    checks:{oilLevel:row(157.2,601.8),coolantLevel:row(157.2,587),batteryCorrosion:row(157.2,572.5),oilLeaks:row(157.2,557.8),brakeFluidLeaks:row(157.2,543),airFilter:row(157.2,528.5),windshield:row(157.2,484.5),wiperBlades:row(307.2,601.8),horn:row(307.2,587),mirrors:row(307.2,572.5),hazardLights:row(307.2,557.8),headlights:row(307.2,543),hiBeam:row(307.2,528.5),taillights:row(307.2,513.8),brakeLights:row(307.2,499),turnSignals:row(307.2,484.5),cleanClear:row(148.2,415.2),locksProperly:row(152.2,378.2),liftSupports:row(152.2,364.2),ladderRack:row(152.2,336.2),hose:row(317.2,416.2),electricHoseReel:row(317.2,401.2),hoseReelGrease:row(317.2,386.2),screenFilter:row(317.2,371.2),sprayGun:row(317.2,356.2),tightenHoseClamps:row(529.2,432.2),runPumpLeaks:row(529.2,415.2),bgsNoLeaks:row(529.2,385.2),hoseFilter:row(529.2,370.2),servicedRegularly:row(529.2,355.2),labeled:row(435.2,343.2),maintainedProperly:row(545.2,343.2),safetyGlasses:row(162.2,299.2),spareClothes:row(162.2,285.2),pesticideGloves:row(357.2,299.2),nonPesticideGloves:row(357.2,285.2),mixingApron:row(535.2,299.2),polyOvershoes:row(535.2,285.2),respiratorContainer:row(535.2,271.2),cellPhone:row(162.2,231.2),vehicleCameraSystem:row(162.2,214.2),printerCondition:row(355.2,231.2),camerasAdjusted:row(355.2,214.2),printerPaper:row(535.2,231.2),workingProperly:row(535.2,214.2),medicalPosting:row(172.2,172.2),labelSdsAccess:row(172.2,158.2),spillKit:row(172.2,144.2),eyeWash:row(172.2,130.2),fireExtinguisher:row(172.2,116.2),measuringDevice:row(172.2,102.2),serviceContainersLabeled:row(172.2,88.2),flashlight:row(365.2,172.2),properBelt:row(365.2,144.2),safetyCone:row(365.2,94.2),currentRegistration:row(545.2,154.2),currentInsurance:row(545.2,139.2),wheelsPacket:row(545.2,124.2),gasCard:row(545.2,109.2),importantPapersEnvelope:row(545.2,94.2)},
    ad:{bodyCondition:{x:170,y:513.5},decalCondition:{x:170,y:499},vehicleInteriorClean:{x:533.5,y:597.5},paperworkOrganized:{x:533.5,y:583.5},cleanOrganized:{x:152.2,y:350.2},appearance:{x:317.2,y:431.2},applicationEquipmentClean:{x:534.8,y:355.2},bgsClean:{x:459,y:385.2},bgsWorking:{x:459,y:370.2},idBadge:{x:383,y:156.2},blackPolishedShoes:{x:383,y:124.2},cleanClarkHat:{x:383,y:108.2}},
    tires:[{pressure:{x:405,y:537.4},tread:{x:497,y:537.4},wear:{x:543,y:541.4}},{pressure:{x:405,y:523.2},tread:{x:497,y:523.2},wear:{x:543,y:527.2}},{pressure:{x:405,y:508.5},tread:{x:497,y:508.5},wear:{x:543,y:512.5}},{pressure:{x:405,y:494.2},tread:{x:497,y:494.2},wear:{x:543,y:498.2}},{pressure:{x:405,y:480.2},tread:{x:497,y:480.2},wear:{x:543,y:484.2}}],
    respirators:{'R/N 95':{x:138,y:269},'N 100':{x:230,y:269},'P 100':{x:321,y:269},'N/A':{x:396,y:269}}
  };
  function row(x,y){return{ok:{x,y},x:{x:x+12,y},na:{x:x+24,y}}}

  function getState(){
    const fd=new FormData(form);const fields={};const values={};const tires=[];
    fieldIds.forEach(id=>fields[id]=fd.get(id)||'');fields.respiratorChoices=fd.getAll('respiratorChoices');fields.respiratorChoice=fields.respiratorChoices.join(', ');
    statusIds.concat(adIds).forEach(id=>values[id]=fd.get(id)||'');
    for(let i=0;i<5;i++){tires.push({pressure:fd.get(`tire${i}_pressure`)||'',tread:fd.get(`tire${i}_tread`)||'',wear:fd.get(`tire${i}_wear`)||''})}
    return{fields,values,tires};
  }
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(getState()));updateProgress();document.getElementById('saveText').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
  function radioByValue(name,value){return Array.from(form.querySelectorAll(`input[name="${name}"]`)).find(el=>el.value===value)}
  function load(){try{const st=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.entries(st.fields||{}).forEach(([k,v])=>{if(k==='respiratorChoices'||k==='respiratorChoice')return;const el=form.elements[k];if(el&&!el.length)el.value=v||''});Object.entries(st.values||{}).forEach(([k,v])=>{if(v){const el=radioByValue(k,v);if(el)el.checked=true;}});const savedChoices=Array.isArray(st.fields&&st.fields.respiratorChoices)?st.fields.respiratorChoices:(st.fields&&st.fields.respiratorChoice?[st.fields.respiratorChoice]:[]);savedChoices.forEach(v=>{const el=Array.from(form.querySelectorAll('input[name="respiratorChoices"]')).find(input=>input.value===v);if(el)el.checked=true;});(st.tires||[]).forEach((t,i)=>{['pressure','tread'].forEach(f=>{const el=form.elements[`tire${i}_${f}`];if(el)el.value=t[f]||''});if(t.wear){const el=radioByValue(`tire${i}_wear`,t.wear);if(el)el.checked=true;}})}catch(e){console.warn('Load failed',e)}updateProgress();}
  function updateProgress(){const st=getState();let total=[];fieldIds.forEach(id=>total.push(st.fields[id]));statusIds.concat(adIds).forEach(id=>total.push(st.values[id]));st.tires.forEach(t=>total.push(t.pressure,t.tread,t.wear));total.push((st.fields.respiratorChoices||[]).length?'yes':'');const done=total.filter(Boolean).length;const pct=Math.round(done/total.length*100);document.getElementById('progressFill').style.width=pct+'%';document.getElementById('progressText').textContent=pct+'% complete';}
  function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastEl.classList.remove('show'),1800)}
  function markOk(ids){ids.forEach(id=>{if(!form.querySelector(`input[name="${id}"]:checked`)){const ok=form.querySelector(`input[name="${id}"][value="OK"]`);if(ok)ok.checked=true;}});save();toast('Marked remaining OK')}
  function clearForm(){if(!confirm('Clear this inspection form?'))return;form.reset();localStorage.removeItem(STORAGE_KEY);updateProgress();toast('Form cleared')}

  form.addEventListener('input',save);form.addEventListener('change',save);
  document.getElementById('markAllOk').addEventListener('click',()=>markOk(statusIds));
  document.querySelectorAll('[data-mark-ok]').forEach(btn=>btn.addEventListener('click',()=>markOk(sectionStatus[btn.dataset.markOk]||[])));
  document.getElementById('clearForm').addEventListener('click',clearForm);
  document.getElementById('previewPdf').addEventListener('click',async()=>{try{setBusy(true,'Building preview...');const blob=await makePdf();const st=getState();const name=`monthly-truck-inspection-${clean(st.fields.date||new Date().toISOString().slice(0,10))}-${clean(st.fields.vehicleLicense||'truck')}.pdf`;const url=URL.createObjectURL(blob);showOutput('Preview ready',url,name);const win=window.open(url,'_blank');if(!win)toast('Preview is ready below. Tap Open PDF.');else toast('Preview opened');}catch(e){showOutputError(e.message||String(e));alert(e.message||String(e))}finally{setBusy(false)}});
  document.getElementById('exportPdf').addEventListener('click',async()=>{try{setBusy(true,'Building PDF...');const blob=await makePdf();const st=getState();const name=`monthly-truck-inspection-${clean(st.fields.date||new Date().toISOString().slice(0,10))}-${clean(st.fields.vehicleLicense||'truck')}.pdf`;const url=URL.createObjectURL(blob);showOutput('PDF ready',url,name);if(navigator.share&&navigator.canShare){const file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'Truck Inspection PDF'});toast('PDF ready');return}}const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();toast('PDF ready. If nothing downloaded, tap Download PDF below.')}catch(e){showOutputError(e.message||String(e));alert(e.message||String(e))}finally{setBusy(false)}});
  function clean(s){return String(s).trim().replace(/[^a-z0-9-_]+/gi,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').toLowerCase()||'blank'}
  function b64ToBytes(b64){const bin=atob(String(b64).replace(/\s/g,''));const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}
  function setBusy(isBusy,msg){['previewPdf','exportPdf'].forEach(id=>{const btn=document.getElementById(id);if(btn)btn.disabled=isBusy});if(isBusy&&msg)toast(msg)}
  function showOutput(title,url,name){const box=document.getElementById('exportOutput');if(!box)return;box.hidden=false;box.innerHTML=`<strong>${title}</strong><div class="output-links"><a href="${url}" target="_blank" rel="noopener">Open PDF</a><a href="${url}" download="${name}">Download PDF</a><button type="button" id="closeOutput">Close</button></div>`;const close=document.getElementById('closeOutput');if(close)close.addEventListener('click',()=>{box.hidden=true});}
  function showOutputError(message){const box=document.getElementById('exportOutput');if(!box)return;box.hidden=false;box.innerHTML=`<strong>Export problem</strong><p>${String(message).replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}</p><div class="output-links"><button type="button" id="closeOutput">Close</button></div>`;const close=document.getElementById('closeOutput');if(close)close.addEventListener('click',()=>{box.hidden=true});}
  function loadScript(src){return new Promise((resolve,reject)=>{const existing=Array.from(document.scripts).find(s=>s.src===src);if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error('Failed to load '+src)),{once:true});return;}const script=document.createElement('script');script.src=src;script.async=true;const timer=setTimeout(()=>{script.remove();reject(new Error('Timed out loading PDF library'))},15000);script.onload=()=>{clearTimeout(timer);resolve()};script.onerror=()=>{clearTimeout(timer);reject(new Error('Failed to load PDF library'))};document.head.appendChild(script);});}
  async function ensurePdfLib(){if(window.PDFLib)return;throw new Error('The local PDF export engine did not load. Re-upload the whole folder, including js/pdf-lib.min.js, then refresh this page.');}
  
  async function makePdf(){await ensurePdfLib();const {PDFDocument,StandardFonts,rgb}=window.PDFLib;const st=getState();const doc=await PDFDocument.load(b64ToBytes(window.TRUCK_TEMPLATE_PDF_BASE64));const pages=doc.getPages();const font=await doc.embedFont(StandardFonts.Helvetica);const bold=await doc.embedFont(StandardFonts.HelveticaBold);const black=rgb(0,0,0);const draw=(p,v,x,y,size=9)=>{v=String(v||'').trim();if(v)pages[p].drawText(v,{x,y,size,font,color:black,maxWidth:220})};const center=(p,v,x,y,size=11)=>{v=String(v||'').trim();if(!v)return;const w=bold.widthOfTextAtSize(v,size);pages[p].drawText(v,{x:x-w/2,y:y-size/2+1.5,size,font:bold,color:black})};const check=(p,x,y)=>{pages[p].drawLine({start:{x:x-4.5,y:y},end:{x:x-1.2,y:y-3.2},thickness:1.8,color:black});pages[p].drawLine({start:{x:x-1.2,y:y-3.2},end:{x:x+5.2,y:y+4.3},thickness:1.8,color:black})};Object.entries(PDF_MAP.text).forEach(([id,spots])=>spots.forEach(pos=>draw(pos.page,st.fields[id],pos.x,pos.y,pos.size||9)));Object.entries(PDF_MAP.checks).forEach(([id,c])=>{const v=st.values[id];if(!v)return;const spot=v==='OK'?c.ok:v==='X'?c.x:c.na;check(0,spot.x,spot.y)});Object.entries(PDF_MAP.ad).forEach(([id,pos])=>{const v=st.values[id];center(0,v,pos.x,pos.y,v==='N/A'?8:11)});PDF_MAP.tires.forEach((m,i)=>{const t=st.tires[i]||{};draw(0,t.pressure,m.pressure.x,m.pressure.y,8);draw(0,t.tread,m.tread.x,m.tread.y,8);center(0,t.wear,m.wear.x,m.wear.y,11)});(st.fields.respiratorChoices||[]).forEach(choice=>{if(PDF_MAP.respirators[choice]){const r=PDF_MAP.respirators[choice];check(0,r.x,r.y)}});return new Blob([await doc.save()],{type:'application/pdf'})}
  load();
})();
